### ISSUE TITLE
oqs provider on windows 

### ISSUE THREAD

**Issue by spellbam** [open-quantum-safe/oqs-provider#495] opened 2024-08-24 10:19 UTC
**Describe the bug**
I have configured oqs provider in openssl 3.2.2  and oqsprovider.dll is located at C:\Users\xyz\Desktop\openssl\openssl-3.2.2\ossl-modules 
after follwing instructions  from here https://github.com/open-quantum-safe/oqs-provider?tab=readme-ov-file

upon running this command "openssl list -providers"
I am getting 
only default providers and not oqs provider

I have cloned oqs-provider with tag number as 0.6.1
and liboqs with tag number as 0.10.1

**Comment by baentsch** [comment] 2024-08-24 15:48
Closing as duplicate of #497.

**Closed by baentsch** 2024-08-24 15:48 UTC
Labels: bug
